# .github/workflows/build.yml

name: Build Rust Project

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      

      - name: Build
        run: cargo build --verbose --release

      - name: Run tests
        run: cargo test --verbose

      - name: Package and upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: rshtml-analyzer-${{ runner.os }}
          path: |
            ${{ github.workspace }}/target/release/rshtml-analyzer${{ runner.os == 'Windows' && '.exe' || '' }}
